// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBG_SgRcjlFFpLRN2PABq3_ogwiStnDto',
    appId: '1:56281189470:web:214224f9646d7361fc38cf',
    messagingSenderId: '56281189470',
    projectId: 'crushera-66e70',
    authDomain: 'crushera-66e70.firebaseapp.com',
    storageBucket: 'crushera-66e70.appspot.com',
    measurementId: 'G-ZJLPW6TFPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfSINIHNUZVucRG8SNu1nS8qq-hdMje84',
    appId: '1:56281189470:android:2526573d779c1225fc38cf',
    messagingSenderId: '56281189470',
    projectId: 'crushera-66e70',
    storageBucket: 'crushera-66e70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1C-gzG3lnd_kqHRrSpj3EnHfXV37H_aE',
    appId: '1:56281189470:ios:624cd4ba1ef4a204fc38cf',
    messagingSenderId: '56281189470',
    projectId: 'crushera-66e70',
    storageBucket: 'crushera-66e70.appspot.com',
    iosBundleId: 'com.example.lovebyteioit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1C-gzG3lnd_kqHRrSpj3EnHfXV37H_aE',
    appId: '1:56281189470:ios:f70efd46c890d2eefc38cf',
    messagingSenderId: '56281189470',
    projectId: 'crushera-66e70',
    storageBucket: 'crushera-66e70.appspot.com',
    iosBundleId: 'com.example.lovebyteioit.RunnerTests',
  );
}
